### ISSUE TITLE
Conda OSX loading problems

### ISSUE THREAD

**Issue by rainman110** [tpaviot/smesh#45]
The smesh conda packages cannot be loaded by python. The _SMESH package cannot be imported, as the libraries are not properly fixed up.

The error are similar to:
```
Traceback (most recent call last):
  File "/Users/martin/Documents/miniconda/envs/pythonocc-nightly/lib/python3.6/site-packages/OCC/SMESH.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/Users/martin/Documents/miniconda/envs/pythonocc-nightly/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: dlopen(/Users/martin/Documents/miniconda/envs/pythonocc-nightly/lib/python3.6/site-packages/OCC/_SMESH.so, 2): Library not loaded: libMEFISTO2.3.dylib
  Referenced from: /Users/martin/Documents/miniconda/envs/pythonocc-nightly/lib/libStdMeshers.3.0.0.dylib
```
You should enable binary relocation of use install_name_tool to fix these problems.

**Comment by rainman110** [comment]
The issue is fixed as of 672518002ae650ff6666eb5e3c93d5a2f3ab9bc6. We just need a recent conda package and compile pythonocc again against smesh.
